package view;


import model.ConnectionFactory;
import model.SistemaComuns;
import model.Produto;
import model.Venda;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.MutableComboBoxModel;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author cfelix
 */
public class VendaVisual extends javax.swing.JFrame {

    ResultSet rs = null;
    PreparedStatement stm = null;
    Venda v = new Venda();
    Produto p = new Produto();
    SistemaComuns sc = new SistemaComuns();

    /**
     * Creates new form VendaVisual
     */
    public VendaVisual() {
        initComponents();
        preencherComboProduto();
        preencherComboCliente();
        consultarQuantidade();
        carregarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtQtd = new javax.swing.JTextField();
        lblTotal = new javax.swing.JLabel();
        cmbCliente = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        cmbProd = new javax.swing.JComboBox<>();
        lblQtdMax = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Produto");

        jLabel2.setText("Cliente");

        jLabel3.setText("Quantidade");

        jLabel4.setText("Valor Total");

        txtQtd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtdActionPerformed(evt);
            }
        });
        txtQtd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtQtdKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQtdKeyReleased(evt);
            }
        });

        lblTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jButton1.setText("Cadastrar Venda");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cmbProd.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbProdItemStateChanged(evt);
            }
        });
        cmbProd.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cmbProdPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cmbProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cmbProdMouseReleased(evt);
            }
        });
        cmbProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProdActionPerformed(evt);
            }
        });

        lblQtdMax.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Data", "Cliente", "Produto", "Quantidade", "Valor Total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel5.setText("Quantidade em Estoque");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel1)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(jLabel3)))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cmbCliente, 0, 91, Short.MAX_VALUE)
                                        .addComponent(cmbProd, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(txtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(39, 39, 39)))
                        .addGap(137, 137, 137)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblQtdMax)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cmbProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(68, 68, 68)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel5)
                        .addGap(1, 1, 1)
                        .addComponent(lblQtdMax, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotal)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        cadastrar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtQtdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtdActionPerformed

    private void txtQtdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtdKeyPressed

    }//GEN-LAST:event_txtQtdKeyPressed

    private void txtQtdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtdKeyReleased

        quantidadeConsulta();   
    }//GEN-LAST:event_txtQtdKeyReleased

    private void cmbProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProdActionPerformed


    }//GEN-LAST:event_cmbProdActionPerformed

    private void cmbProdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbProdItemStateChanged

    }//GEN-LAST:event_cmbProdItemStateChanged

    private void cmbProdMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbProdMouseReleased

    }//GEN-LAST:event_cmbProdMouseReleased

    private void cmbProdPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmbProdPopupMenuWillBecomeInvisible
        consultarQuantidade();
    }//GEN-LAST:event_cmbProdPopupMenuWillBecomeInvisible
    public void cadastrar() {
        String id_prod[] = new String[2];
        String id_cli[] = new String[2];
        id_prod = ((String) cmbProd.getSelectedItem()).split("-");
        id_cli = ((String) cmbCliente.getSelectedItem()).split("-");
        
        if (Integer.parseInt(txtQtd.getText()) >= 0 && txtQtd.getText().matches("^(\\d)+$")){
            
            v.cadastrarVenda(Integer.parseInt(id_prod[0]), Integer.parseInt(id_cli[0]), Integer.parseInt(txtQtd.getText()), Double.parseDouble(lblTotal.getText()),sc.coletarDataSistema());
            carregarTabela();
            consultarQuantidade();
        } else {
            JOptionPane.showMessageDialog(null, "A quantidade não pode ser negativa e precisa ser um numero");
        }
        limparCampos();

    }

    public void quantidadeConsulta() {
        String id_prod[] = new String[2];
        double valor = 0;
        id_prod = ((String) cmbProd.getSelectedItem()).split("-");
        valor = p.valorProduto(Integer.parseInt(id_prod[0]));
        double qtd = 0;
        if (txtQtd.getText().isEmpty()) {
            qtd = 0;    
        } else if ( txtQtd.getText().matches("^(\\d)+$")) {
            qtd = Double.parseDouble(txtQtd.getText());
        }else{
            qtd=0;
            txtQtd.setText("0");
        JOptionPane.showMessageDialog(null,"A quantidade precisa ser um numero");
        }
        lblTotal.setText(String.valueOf(qtd * valor));

    }

    public void preencherComboProduto() {

        Connection con = ConnectionFactory.getConnection();
        Object dados[] = new Object[2];
        try {

            stm = con.prepareStatement("SELECT * FROM produto");
            rs = stm.executeQuery();
            while (rs.next()) {
                dados[0] = rs.getInt("prod_id");
                dados[1] = rs.getString("prod_desc");
                cmbProd.addItem(dados[0] + "-" + dados[1]);
            }

        } catch (SQLException ex) {
            Logger.getLogger(VendaVisual.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void preencherComboCliente() {
        Connection con = ConnectionFactory.getConnection();
        Object dados[] = new Object[2];
        try {
            stm = con.prepareStatement("SELECT * FROM cliente");
            rs = stm.executeQuery();
            while (rs.next()) {
                dados[0] = rs.getInt("id_cli");
                dados[1] = rs.getString("nome_cli");
                cmbCliente.addItem(dados[0] + "-" + dados[1]);
            }
        } catch (SQLException ex) {
            Logger.getLogger(VendaVisual.class.getName()).log(Level.SEVERE, null, ex);
        }
        ConnectionFactory.closeConnection(con, stm);

    }

    public void consultarQuantidade() {
        String id_prod[] = new String[2];
        id_prod = ((String) cmbProd.getSelectedItem()).split("-");
        lblQtdMax.setText(String.valueOf(p.consultarQuantidadeProduto(Integer.parseInt(id_prod[0]))));
    }

    public void limparCampos() {

        txtQtd.setText("0");

    }

    private void carregarTabela() {
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setNumRows(0);
        Connection con = ConnectionFactory.getConnection();
        ResultSet rs = null;
        Object dados[] = new Object[6]; // seis posições, seis colunas
        PreparedStatement stm = null;
        try {
            stm = con.prepareStatement("SELECT id_venda,prod_desc, nome_cli,qtd_prod_vend,vTotal_venda,data_venda FROM venda inner join produto on id_produto=prod_id INNER JOIN cliente on id_cliente =id_cli order by data_venda");
            rs = stm.executeQuery();
            while (rs.next()) {
                dados[0] = rs.getInt("id_venda");
                dados[1] = rs.getString("prod_desc");
                dados[2] = rs.getString("nome_cli");
                dados[3] = rs.getInt("qtd_prod_vend");
                dados[4] = rs.getDouble("vTotal_venda");
                dados[5] = rs.getString("data_venda");
                modelo.addRow(dados);
            }
        } catch (SQLException ex) {
            Logger.getLogger(VendaVisual.class.getName()).log(Level.SEVERE, null, ex);
        }
        ConnectionFactory.closeConnection(con, stm, rs);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VendaVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VendaVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VendaVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VendaVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VendaVisual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbCliente;
    private javax.swing.JComboBox<String> cmbProd;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblQtdMax;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTextField txtQtd;
    // End of variables declaration//GEN-END:variables
}
